# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d84d6d86b60da9b5cd79afe308326028545b015cd8f42d9f9554f9186641faf113d83897fe3551b92b293e320b9165627403a65c5847405ecfe6541ba9f50369

test:
  secret_key_base: b299635b1bf38dffbbf377805367e96c0bac5e3e9ba2d930e3c38502371c6c4101e07a4c4c07ef67f6a27cb4135db9808012c0fc229a260681b5f8b491268bc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
